GET http://homebrain2/api/sensors/get
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2OTc4MjQzOTYsImV4cCI6MTY5NzgyNzk5Niwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiZTAwMSJ9.Dss_6IEjm3yQ6PPj8UvCYHGDf0KaNndwH2Ct4cmJfFbjs9hB5oJ_4UA_P3lCYRUO9y4dh6j1gh1etVRCi8VvZEEjAIVaqm-qFlkUHNNEu1k8_ja_I9DnfjJjeT8YF8MeMJpNfDPyrD_m_yeVCgCN1C48i8CkuQF7eAVJuvWW0OaCObPMUFCyKbzPfA4DZURrRNkkTYlb_3YJJ9KJiO6yOLKL7K-WPPy3WYdPsNrZ8jlvGENWVwZR6vlJMEkP36Otib9nea1PMGHoQkJmcXBJbuxihs6wcs9mxP_cciq1Mu3W2lRX7wfOhEqQYWBpbNqS5z7Pom3eAkSe1lQNzyt8Cw
Content-Type: application/json