GET http://homebrain2/api/devices/get
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2OTY3ODU5NjIsImV4cCI6MTY5Njc4OTU2Miwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiZTAwMSJ9.go8cRcJJ3UOpuQl-_thxs2saPSGDmIfl6T_O31U1VvWNYcEmRJtfFZVtTGiso_MHCkDWPmtjSPiO7U-ZcBVQcLxVmjpf2_WyZnwOzw8wbzai5EFgEllxsDUX-wlQd1J4yOh8wU4el66q3m1sWtRtXMDSARSQiQdlHZYCL_GKNlnwYSFe5ocRGwiaLX9QMfK74wEi1Q3mIoCM4E1IKaRam7EuTZ52MQSql3k1WbsUIfpOSN_FltLqsG7elT3QGQFG15S6vfnDhyqO3G6YaOj8iC6TovhL3LmBFM3Dc247F5wVX7Z-xXKlvIQKcGHPC-CQEVKmYPY1jFSsCqzN92HTUg
Content-Type: application/json