GET http://homebrain2/api/sensors/get
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2OTY2MDQ2NjUsImV4cCI6MTY5NjYwODI2NSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiZTAwMSJ9.FEa_MInOp30VbVp4YfCaoQ-lFSj6V4QSyhjhJHb9TG-Z3OXMPzdEoOj0OZUobxyo7zBFCqum20MBXnYOh02Xn3KRPWFSdcUj799SYv5YwtJNelgzGB5DtQiNwC_99CRjkUMHy9W-l206C-a_TyitaiJQLK_ySyLKLlNIX7VtRoMCfZPXZ5NEiQSrmZenI9ud87ZhrWW05_cAQuYuhMZSHJz1ge4rxSbx16I4Z_WMsBmO8sXVFNO83vTyO2oI8W10TYQPvmhwuT0J8fGLd7PIyY-VXPtaAb3JNH2XjFkBGUk7HdSOZoUs6QNANbx2Vc_hO4wzB0eEBFAx9LQEMuo-Vg
Content-Type: application/json