GET http://homebrain2/api/sensors/get
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2OTkzNzY0MTgsImV4cCI6MTY5OTM4MDAxOCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiZTAwMSJ9.C7LbZxssGyBgefRHs0jS9n5ou9eXzNKHlKBefT5qE5LxP6aWP80BjSjTAdAyQPoD4Oqvi6vfztCCYFMZKLtecvxeAy6NIR5CllVdy3Od74ck0GtJBkRAH1rd8768caJ_KE0RfHRodhCdLmR5q5C7otD-NqxMXanZo45b7l3xDfLO0iP3XfF8d6wLqjXOwgZKAOgjxWtFwCV5VrrQhW6dQLTodY06bqbSIPPSbkwp85aHcKsa8AFiTNjyomMxL3lBRQPnkq3cYwbFUD6ySIUc4_JnWS-xGtbWTIurfC7Y3lTWef3_1EsWNg6Zov3lhlrPETcv8V4fZHFdBdwB1Fhc1w
Content-Type: application/json