### GET request with a header
GET http://homebrain2/api/api_hello
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2OTY0MzUzNDgsImV4cCI6MTY5NjQzODk0OCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiZTAwMSJ9.aNSJtGMlYo9uPw2hdEe_q8z_Ws1S1NIozGdrU5SOqfw82J1812L7wYPQpQahY2UF3JPX_oMVd4GgjirDrJsToQtHJ9p5oMO9-eyDo7mULEVN1EV0VDm6kRIb2Z9N104k4qEhPB8wsrnxGdDTUiOPQRRNRJhm99WKwJPlNaf6aNPI5stw2LK-9p38oNk7JN1LCBGi87xLokOnt1H_X35w120mt2rwfYRMylqWalEj3_rs3n5zLXBMsM3PMyRCWrVFAW6OLG27iDXCbV_ygliD1-TLTl949G0Hf7hgHmFntvE2EvXGYaMLm28vZkq0dUUbipwFm8ypIuAxXCGP_Ja3eg
Content-Type: application/json
