#App
index:
  path: /
  controller: App\Controller\AppController::index

app_login:
  path: /login
  controller: App\Controller\UserController::login

app_registration:
  path: /registration
  controller: App\Controller\UserController::registration

user_change_data:
  path: /user/data/change
  controller: App\Controller\UserController::change

app_logout:
  path: /logout

app_login_check:
  path: /login/check
  controller: App\Controller\UserController::login_check

app_add_location:
  path: /location/add
  controller: App\Controller\AppController::addLocation

app_dashboard:
  path: /dashboard
  controller: App\Controller\AppController::dashboard

app_notices:
  path: /notices
  controller: App\Controller\AppController::notices

app_location_change_data:
  path: /location/data/change
  controller: App\Controller\AppController::changeLocation

app_location:
  path: /location
  controller: App\Controller\AppController::location

app_get_publisher:
  path: /location/{location}/get/publisher
  controller: App\Controller\AppController::getPublishers
  requirements:
    location: '\d+'

app_edit_publisher:
  path: /publisher/{publisher}/edit
  controller: App\Controller\AppController::editPublisher
  requirements:
    publisher: '\d+'

app_get_location:
  path: /location/{location}/get
  controller: App\Controller\AppController::getLocation
  requirements:
    location: '\d+'

app_edit_location:
  path: /location/{location}/edit
  controller: App\Controller\AppController::editLocation
  requirements:
    location: '\d+'

app_location_delete:
  path: /location/{location}/delete
  controller: App\Controller\AppController::deleteLocation
  requirements:
    location: '\d+'

app_add_publisher:
  path: /publisher/add
  controller: App\Controller\AppController::addPublisher

app_delete_publisher:
  path: /publisher/{publisher}/delete
  controller: App\Controller\AppController::deletePublisher

app_edit_plate:
  path: /plate/{plate}/edit
  controller: App\Controller\AppController::editPlate
  requirements:
    plate: '\d+'

app_delete_plate:
  path: /plate/{plate}/delete
  controller: App\Controller\AppController::deletePlate
  requirements:
    plate: '\d+'

app_plate_change_data:
  path: /plate/{plate}/change
  controller: App\Controller\AppController::changePlate
  requirements:
    plate: '\d+'

user_account:
  path: /user/account
  controller: App\Controller\UserController::account

user_add_plate:
  path: /user/addPlate
  controller: App\Controller\UserController::regIOT

api_login_check:
  path: /api/api-authentication

api_hello:
  path: /api/api-hello
  controller: App\Controller\IntegratedSystemController::helloWorld

api_get_sensors:
  path: /api/sensors/get
  controller: App\Controller\IntegratedSystemController::getSensors

api_get_devices:
  path: /api/devices/get
  controller: App\Controller\IntegratedSystemController::getDevices

arduino_immitation:
  path: /arduino/imitation
  controller: App\Controller\AppController::arduinoImitation